---
kind: pipeline
name: build
workspace:
  base: /go
  path: src/github.com/suzuki-shunsuke/flute
steps:
- name: durl
  image: quay.io/suzuki_shunsuke/durl:1.0.0
  commands:
  - sh scripts/durl.sh
- name: download go modules
  image: &image_go golang:1.12.9
  commands:
  - go mod download
  environment:
    GO111MODULE: on
    GOPATH: /go
- name: golangci-lint
  image: golangci/golangci-lint:v1.17.1
  commands:
  - golangci-lint run
  environment:
    GO111MODULE: on
    GOPATH: /go
- name: codecov
  image: *image_go
  commands:
  # bash and cgo seem to be required
  - bash scripts/codecov-test.sh
  - curl -s https://codecov.io/bash > /tmp/codecov.sh
  - test "$LOCAL" = "true" -o "$DRONE_BUILD_EVENT" = "pull_request" || bash /tmp/codecov.sh
  environment:
    GO111MODULE: on
    GOPATH: /go
    CODECOV_TOKEN:
      from_secret: codecov_token
