---
kind: pipeline
name: build
clone:
  depth: 1
volumes:
- name: gopath
  temp: {}
steps:
- name: durl
  image: quay.io/suzuki_shunsuke/durl:1.0.0@sha256:2753542727d8e68a823dece28f60bc0bae7d0ebac291e3563939802ff2bef6c0
  commands:
  - sh scripts/durl.sh
- name: download go modules
  image: golang:1.24.1@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  commands:
  - go mod download
  volumes: &volumes
  - name: gopath
    path: /go
- name: golangci-lint
  image: golangci/golangci-lint:v1.64.6-alpine@sha256:65e406735929c1c52f71e5b5524644627fb03538fc32c2119e193512ad78adbb
  commands:
  - golangci-lint run
  volumes: *volumes
- name: benchmark
  image: golang:1.24.1@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  commands:
  - cd flute
  - go test -bench=. -benchmem
  volumes: *volumes
- name: codecov
  image: golang:1.24.1@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  commands:
  # bash and cgo seem to be required
  - bash scripts/codecov-test.sh
  - curl -s https://codecov.io/bash > /tmp/codecov.sh
  - test "$LOCAL" = "true" -o "$DRONE_BUILD_EVENT" = "pull_request" || bash /tmp/codecov.sh
  volumes: *volumes
  environment:
    CODECOV_TOKEN:
      from_secret: codecov_token
