version: "2"
linters:
  default: all
  disable:
    - depguard
    - err113
    - exhaustruct
    - gocritic
    - mnd
    - nlreturn
    - paralleltest
    - revive
    - testifylint
    - thelper
    - varnamelen
    - wrapcheck
    - wsl
    - godot
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - flute/mock_round_tripper_test.go
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - flute/mock_round_tripper_test.go
      - third_party$
      - builtin$
      - examples$
