---
name: test
on: pull_request
permissions: {}
jobs:
  status-check:
    runs-on: ubuntu-24.04
    if: failure()
    timeout-minutes: 10
    permissions: {}
    needs:
      - test
    steps:
      - run: exit 1
  test:
    uses: suzuki-shunsuke/go-test-full-workflow/.github/workflows/test.yaml@b580b4ccd8411e21a246036b7cd486e4af516a7b # v3.1.0
    with:
      aqua_version: v2.46.0
    permissions:
      pull-requests: write
      contents: read
