---
name: test
on: pull_request
permissions: {}
jobs:
  status-check:
    runs-on: ubuntu-24.04
    if: always() && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled'))
    timeout-minutes: 10
    permissions: {}
    needs:
      - test
    steps:
      - run: exit 1
  test:
    uses: suzuki-shunsuke/go-test-full-workflow/.github/workflows/test.yaml@8aaae7f33a80bbc1b51a67b4b7fd6e724ce11201 # v3.2.3
    with:
      aqua_version: v2.53.9
    permissions:
      pull-requests: write
      contents: read
